name: Calling Reusable Workflows
run-name: "Calling Reusable Workflows @${{github.actor}}"
on: 
    workflow_dispatch:
        inputs:
            name:
                description: "Give your name"
                type: string
                default: "Pierre"
                required: true 

jobs:
    calling-a-reusable-wk:
        uses: nogatygroups/github-actions/.github/workflows/reusable-wkf.yml@f272968c3744dfba00fa8e98163060f92ae24906
        with:
            name: ${{inputs.name}}
        secrets:
            access_token: ${{secrets.NOGATY_SECRET}}
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wk
        steps:
            - run: echo ${{needs.calling-a-reusable-wk.outputs.date}}
