name: Concurrency 1
run-name: "Environment ${{inputs.environment}} concurrency 1 @${{github.actor}}, event: ${{github.event_name}}"
on:
    workflow_dispatch:
        inputs: 
            environment: 
                description: "Environment"
                type: environment
                required: true 
   
concurrency:
    group: ${{inputs.environment}}
    cancel-in-progress: true
jobs:
    sleep-job:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30
            - run: |
                echo "Test entre ${{inputs.environment}} et ${{github.event.inputs.environment}}"