name: Default and Custom Environment Variable
run-name: "Default and Custom Environment Variable @${{github.actor}}, Event: ${{github.event_name}}, Github action: ${GITHUB_ACTION}"
on:
    push:
jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
        if: github.ref == 'github.refs/heads/features/feature01'
        steps:
            - name: Log ENV VAR
              id: log_env_vars
              run: |
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_ACTIONS: $GITHUB_ACTION"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "RUNNER_NAME: $RUNNER_NAME"
            - name: Log Context 
              id: log_contexts_vars
              run: |
                echo "github.ref: ${{github.ref}}"
                echo "Repository name is ${{ github.repository }}"
            - name: Log Costum Vars
              env:
                MESSAGE: "Bienvenu Ã  Nogaty Entreprise"
                EMAIL: "houlouwolopierre@nogaty-entreprise.fr"
              run: |
                echo "MESSAGE: ${{env.MESSAGE}}"
                echo "EMAIL: ${{env.EMAIL}}"
        


