name: Default and Custom Environment Variable
run-name: "Default and Custom Environment Variable @${{github.actor}}, Event: ${{github.event_name}}, Github action: $GITHUB_ACTION"
on:
    push:
jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
        steps:
            - name: Log ENV VAR
              run: |
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
            - name: Log Context 
              run: |
                echo "github.ref: ${{github.ref}}"
                echo "Repository name is ${{ github.repository }}"


