name: Extends pull request permission
run-name: ${{github.actor}}
on: 
    pull_request_target:
        types: [opened]
    #issues:
    #    types: [opened]
permissions:
    issues: read
    #contents: read
jobs:
    Pull-Requests-comment:
        runs-on: ubuntu-latest
        steps: 
            - name: Comment on new pull requests
              uses: actions/github-script@v8
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'Thanks for contributing! @Nogaty Entreprise' ,
                    });