name: Repository Events v2
run-name: ${{github.actor}} 
on: 
    push:
        branches:
            - main
            - "features/*" # matches feature/featA, feature/featB, does not match feature/featA/ , feature/featB/x
            - "features/**" # matches feature/featA, feature/featB, feature/featA/ , feature/featB/
            - "releases/**"
            - "!features/featA" # Except features/featA
        #branches-ignore: # You can may use only: branches, branches-ignore
        #    - develop
        tags:
            - v1
            - v2.*
        # tags-ignore: You can may use only: tags, tags-ignore
        #    - v3
        paths:
            - "**.js"
            - "!app.js"

jobs:
    Check-branches-filtering:
        runs-on: ubuntu-latest
        steps:
            - name: test with checkout
              uses: actions/checkout@v6
            - run: |
                echo $GITHUB_REF
                echo $GITHUB_SHA