name: Github Expression & Contexts 
run-name: "Expressions & contexts by @${{github.actor}} , event: ${{github.event_name}}"
on: [push, pull_request, issues, workflow_dispatch]

jobs:
    uses-expressions-and-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Expression
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'string' }}
                echo ${{ true && false }}
                echo ${{ true || ( false && true ) }}
            - name: Dump Contexts
              id: contexts
              run: |
                echo 'github:<==> ${{ toJson(github) }}'
                echo 'job:<==> ${{ toJson(job) }}'
                echo 'secrets:<==> ${{ toJson(secrets) }}'
                echo 'steps:<==> ${{ toJson(steps) }}'
                echo 'runner:<==> ${{ toJson(runner) }}'
                echo 'Token:<==> ${{ github.token }}'

