name: If key statement 
run-name: "vIf key statement  by @${{github.actor}} , event: ${{github.event_name}}"
on: [push, pull_request, issues, workflow_dispatch]

jobs:
    uses-if-key-statement:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: If key statement
              id: if_key_statement
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'string' }}
                echo ${{ true && false }}
                echo ${{ true || ( false && true ) }}
            - name: Dump Contexts
              id: contexts
              run: |
                echo 'github:<==> ${{ toJson(github) }}'
                echo 'job:<==> ${{ toJson(job) }}'
                echo 'secrets:<==> ${{ toJson(secrets) }}'
                echo 'steps:<==> ${{ toJson(steps) }}'
                echo 'runner:<==> ${{ toJson(runner) }}'
                echo 'Token:<==> ${{ github.token }}'