name: Reusable workflow
run-name: "Reusable workflow @${{github.actor}}"
on: 
    workflow_call:
        inputs:
            name:
                description: "Give your name"
                type: string
                default: "Pierre"
                required: true 
        secrets:
            access_token:
                description: "Access token"
                required: true
    

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: |
                ls -la 
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display github context
              run: echo '${{ toJson(github) }}'
            - name: Display inputs name
              run: echo ${{inputs.name}}
            - name: Display access token secrets
              run: echo ${{ secrets.access_token }}
    generate-output:
        runs-on: ubuntu-latest
        outputs: 
            date: ${{steps.date-step.outputs.date}}
            log-out: ${{steps.log-outputs.outputs}}
        needs: [log-context-and-inputs]
        steps: 
            - id: date-step
              run: echo "date=$(date)" >> $GITHUB_OUTPUT
            - id: log-outputs
              run: |
                echo "${{ needs.log-context-and-inputs.outputs }}" >> $GITHUB_OUTPUT
                echo ${{ needs.log-context-and-inputs.result }} >> $GITHUB_OUTPUT
