name: Reusable workflow
run-name: "Reusable workflow @${{github.actor}}"
on: 
    workflow_call:
        inputs:
            name:
                description: "Give your name"
                type: string
                default: "Pierre"
                required: true 
        secrets:
            access_token:
                description: "Access token"
                required: true
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - run: |
                ls -la 
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display github context
              run: echo '${{ toJson(github) }}'
            - name: Display inputs name
              run: echo ${{inputs.name}}
            - name: Display access token secrets
              run: echo ${{ secrets.access_token }}
              
