name: Run Multiples Jobs Using Matrix
run-name: "Run Multiples Jobs Using Matrix @${{github.actor}} , Event ${{github.event_name}}"
on:
    push:

jobs:
    node-matrix:
        continue-on-error: true
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest,macos-latest]
                node-version: [18,19,20,21,22,23,24]
            # max-parallel: 4
        runs-on: ${{matrix.os}}
        steps:
         - run: node -v 
         - uses: actions/setup-node@v3 
           with:
            node-version: ${{ matrix.node-version}}
         - run: node -v 

