name: Scripting in Github actions 
run-name: "Scripting in Github actions @${{github.actor}}"
on: 
  workflow_dispatch:
    inputs: 
      os: 
        description: Operating Systems
        default: "windows-latest, ubuntu-latest, macos-latest"
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Use github-script action 
        id: script-id
        uses: actions/github-script@v6
        with:
          script: |
            const osArray = context.payload.inputs.os.split(',');
            return { OS: osArray };
          result-encoding: json
      - name: Echo script ID 
        run: |
          echo "step script-output=${{ steps.script-id.outputs.result }}" >> $GITHUB_OUTPUT
          echo "${{ steps.script-id.outputs.result }}"

  
  #matrix-execution:
  #  runs-on: 
  #  steps: