name: Scripting in Github actions 
run-name: "Scripting in Github actions @${{github.actor}}"
on: 
  workflow_dispatch:
    inputs: 
      os: 
        description: Operating Systems
        default: "windows-latest, ubuntu-latest, macos-latest"
        type: string
      node-version:
        description: "Node version"
        default: "22,23,24"
        type: string
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs: 
      matrix-arrays: ${{steps.matrix-array.outputs.result}}
    steps:
      - name: Use github-script action 
        id: matrix-array
        uses: actions/github-script@v6
        with:
          script: "return {'os': context.payload.inputs['os'].split(','),'node-version': context.payload.inputs['node-version'].split(',')}"

          result-encoding: json
      - name: Echo script ID 
        run: |
          echo "step script-output=${{ steps.matrix-array.outputs.result }}" >> $GITHUB_OUTPUT
          echo "${{ steps.matrix-array.outputs.result }}"

  
  node-matrix:
    needs: [prepare-matrix]
    strategy:
        matrix:
            os: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).os}}
            node-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).node-version}}
        fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v 
      - uses: actions/setup-node@v3 
        with:
         node-version: ${{ matrix.node-version}}
      - run: node -v