name: Check functions status
run-name: "Check function status @${{github.actor}}, Event_name: ${{github.event_name}}"
on:
    push:
jobs:
    job-1: 
        runs-on: ubuntu-latest
        steps:
            - name: Step1
              run: sleep 30
            - name: Allow Fail
              run: exit 1
            - name: Runs on Failure
              if: failure()
              run: echo "Runs only if failure"
              # This is needed (DEFAULT BEAHAVIOR)
            - name: Runs on Success
              if: success()
              run: echo "Run job 2"
            - name: Runs on Always
              if: always()
              run: echo "Always Runs"
            - name: Run when Cancelled
              if: cancelled()
              run: echo "Runs on Cancelled"


    job-2: 
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo "Job 2"
