name: Upload and download jobs artifacts
run-name: "Upload and download jobs artifacts @${{github.actor}}, event: ${{github.event_name}}"

on:
    workflow_dispatch:

jobs:
    use-axios:
        runs-on: ${{vars.JOBS_RUNNER}}
        steps:
            - uses: actions/checkout@v5
            - name: Cache node modules
              id: cache-dependencies
              uses: actions/cache@v4
              with:
                path: ./web-project/node_modules
                key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/web-project/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-npm-cache-
                  ${{ runner.os }}-

            - name: Display cache output
              run: |
                echo '${{toJson(steps.cache-dependencies.outputs)}}'
            - name: Install npm dependencies
              run: npm install 
              working-directory: ./web-project     
            - name: Display npm details
              run: npm fund
              working-directory: ./web-project  
            - name: Run Test
              run: npm test
              working-directory: ./web-project
            - name: Upload Code Coverage Report
              uses: actions/upload-artifact@v5
              if: always()
              with:
                name: code-coverage
                path: ./web-project/coverage
                retention-days: 1
            - name: Download Code Coverage
              uses: actions/download-artifact@v5
              with:
                name: code-coverage
                path: code-coverage-report
            - name: Display coverage file content
              run: ls -la *
              working-directory: ./web-project
            - name: Display coverage-report file content
              run: ls -la code-coverage-report/*
              working-directory: ./web-project


            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: |
                  const path = require('path');
                  const targetDir = path.join(process.env.GITHUB_WORKSPACE,'web-project');
                  process.chdir(targetDir);
                  console.log('Repertoir actuel:', process.cwd());
                  const axios = require('axios')
                  const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
                  console.log(res.data)
              

        