name: Use Nogaty Composite Action
on:
  push:

jobs:
  use-composite-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5  #v5

      - name: Use Nogaty composite action
        uses: ./.github/actions/setup-project
        with:
          node-version: '24'
          test-script: 'test'
        
